-- 0. PROFILES TABLE
-- Description: Stores public user data synced from auth.users
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email TEXT,
  full_name TEXT,
  role TEXT CHECK (role IN ('student', 'employer')),
  university TEXT,
  business_name TEXT,
  onboarding_done BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1. JOBS TABLE
-- Description: Stores job listings created by employers.
CREATE TABLE public.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  location TEXT,
  salary DECIMAL(10, 2) DEFAULT 0.00,
  deposit DECIMAL(10, 2) DEFAULT 0.00, -- Commitment fee
  status TEXT DEFAULT 'Open', -- Open, Pending, In Progress, Completed, Closed
  tags TEXT[], -- Array of strings for skills/interests
  deadline DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. APPLICATIONS TABLE
-- Description: Stores student applications for specific jobs.
CREATE TABLE public.applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  message TEXT,
  status TEXT DEFAULT 'pending', -- pending, accepted, rejected, completed
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(job_id, student_id) -- Prevent duplicate applications
);

-- 3. COMMITMENT FEES (TRANSACTIONS)
-- Description: Tracks the refundable fees paid by students.
CREATE TABLE public.commitment_fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES public.jobs(id) ON DELETE SET NULL,
  student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  status TEXT DEFAULT 'Held', -- Held, Refunded, Forfeited
  paid_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  refunded_at TIMESTAMP WITH TIME ZONE
);

-- 4. MARKETPLACE ITEMS
-- Description: Products or services listed by students.
CREATE TABLE public.marketplace_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  type TEXT NOT NULL, -- Product, Service
  category TEXT,
  location TEXT,
  status TEXT DEFAULT 'Ongoing', -- Ongoing, Preorder, Sold
  tags TEXT[],
  rating DECIMAL(2, 1) DEFAULT 0.0,
  reviews_count INT DEFAULT 0,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. RATINGS TABLE
-- Description: Stores reviews and ratings between users.
CREATE TABLE public.ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reviewer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  target_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  job_id BIGINT REFERENCES public.jobs(id) ON DELETE SET NULL,
  rating SMALLINT CHECK (rating >= 1 AND rating <= 5) NOT NULL,
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. MARKETPLACE ORDERS
-- Description: Tracks purchases made in the marketplace.
CREATE TABLE public.marketplace_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT REFERENCES public.marketplace_items(id) ON DELETE SET NULL,
  buyer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  seller_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  quantity INT DEFAULT 1,
  total_amount DECIMAL(10, 2) NOT NULL,
  bank_name TEXT,
  status TEXT DEFAULT 'Completed',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. FUNCTIONS & TRIGGERS
-- Sync auth.users to public.profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role, university, business_name, onboarding_done)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'fullName',
    new.raw_user_meta_data->>'role',
    new.raw_user_meta_data->>'university',
    new.raw_user_meta_data->>'businessName',
    COALESCE((new.raw_user_meta_data->>'onboardingDone')::boolean, false)
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 7. RLS POLICIES (Security)

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commitment_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ratings ENABLE ROW LEVEL SECURITY;

-- Profiles: Users can view their own profile
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Jobs: Everyone can view, but only employers can create/edit their own.
CREATE POLICY "Anyone can view open jobs" ON public.jobs FOR SELECT USING (true);
CREATE POLICY "Employers can insert their own jobs" ON public.jobs FOR INSERT WITH CHECK (auth.uid() = employer_id);
CREATE POLICY "Employers can update their own jobs" ON public.jobs FOR UPDATE USING (auth.uid() = employer_id);

-- Applications: Students can view their own, employers can view apps for their jobs.
CREATE POLICY "Students can view their own applications" ON public.applications FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Employers can view applications for their jobs" ON public.applications FOR SELECT 
  USING (EXISTS (SELECT 1 FROM public.jobs WHERE id = job_id AND employer_id = auth.uid()));
CREATE POLICY "Students can apply" ON public.applications FOR INSERT WITH CHECK (auth.uid() = student_id);

-- Marketplace: Everyone can view, only owners can manage.
CREATE POLICY "Anyone can view marketplace items" ON public.marketplace_items FOR SELECT USING (true);
CREATE POLICY "Users can manage their own marketplace items" ON public.marketplace_items 
  FOR ALL USING (auth.uid() = owner_id);

-- Commitment Fees: Users can view their own.
CREATE POLICY "Users can view their own transactions" ON public.commitment_fees FOR SELECT USING (auth.uid() = student_id);

-- Ratings: Everyone can view, anyone can insert if they are the reviewer.
CREATE POLICY "Anyone can view ratings" ON public.ratings FOR SELECT USING (true);
CREATE POLICY "Users can insert their own ratings" ON public.ratings FOR INSERT WITH CHECK (auth.uid() = reviewer_id);
